services:

  backend:
    build: ./SweetBitesBE/springboot-backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CONTACT_TO_EMAIL: ${CONTACT_TO_EMAIL}

  frontend:
    build: ./SweetBitesFE
    ports:
      - "4200:4200"
    volumes:
      - ./SweetBitesFE:/app
      - /app/node_modules
    command: npm start -- --host 0.0.0.0 --port 4200